kind: pipeline
type: docker
name: default


concurrency:
  limit: 1

steps:

- name: build-atmosphere
  image: appleboy/drone-ssh
  environment:
    GITUSER:
      from_secret: gituser 
    GITPASS:
      from_secret: gitpass 
  settings:
    host: atmosphere.innovare.es
    username:
      from_secret: ssh_dev_user
    password:
      from_secret: ssh_dev_password
    port: 22
    envs:
      - gituser
      - gitpass
    script:
      - cd /home/developer/Atmosphere/Atmosphere/
      - git pull --recurse-submodules https://$${GITUSER}:$${GITPASS}@gogs.innovare.es/INNOVARE/Atmosphere
      - sudo docker build --tag atmosphere:atmosphere .

- name: deploy-atmosphere
  image: appleboy/drone-ssh
  settings:
    host: atmosphere.innovare.es
    username:
      from_secret: ssh_dev_user
    password:
      from_secret: ssh_dev_password
    port: 22
    script:
      - cd /home/developer/Atmosphere/Atmosphere/
      - sudo docker-compose down
      - sudo DRONE_COMMIT=${DRONE_COMMIT} docker-compose up -d
