version: '3'
services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # timezone inside container
      - TZ=UTC
      # necessary Postgres options/variables
      - POSTGRES_USER=atmosphere
      - POSTGRES_PASSWORD=${database_password}
      - POSTGRES_DB=atmosphere
  backend:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - ./migrations:/code/app/migrations
    environment:
      FRONTEND_URL: "https://atmosphere.innovare.es"
      DB_URL: "postgres://atmosphere:${database_password}@postgres:5432/atmosphere"
      DO_KEY: "${do_key}"
    image: "innovaresoftware/atmosphere-runner:latest"
    ports:
      - 3001:80
  frontend:
    depends_on:
      - "backend"
    environment:
      BACKEND_URL: "https://atmosphere-backend.innovare.es"
      COMPILE_VERSION: "${VERSION_TAG}"
    image: "innovaresoftware/atmosphere:latest"
    ports:
     - 3000:3000
    restart: unless-stopped
volumes:
  postgres_data:
    driver: local
